# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('Number', models.BigIntegerField(primary_key=True, serialize=False, verbose_name=b'\xd0\x9d\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80')),
                ('Password', models.IntegerField(verbose_name=b'\xd0\x9f\xd0\xb0\xd1\x80\xd0\xbe\xd0\xbb\xd1\x8c')),
                ('FailCount', models.IntegerField(default=0, verbose_name=b'\xd0\x9e\xd1\x88\xd1\x8b\xd0\xb1\xd0\xbe\xd0\xba \xd0\xb2\xd0\xb2\xd0\xbe\xd0\xb4\xd0\xb0 \xd0\xbf\xd0\xb0\xd1\x80\xd0\xbe\xd0\xbb\xd1\x8f')),
                ('Balance', models.IntegerField(verbose_name=b'\xd0\x91\xd0\xb0\xd0\xbb\xd0\xb0\xd0\xbd\xd1\x81')),
                ('Locked', models.BooleanField(default=False, verbose_name=b'\xd0\x91\xd0\xb0\xd0\xbb\xd0\xb0\xd0\xbd\xd1\x81')),
            ],
            options={
                'db_table': 'BankCard',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateT', models.DateTimeField(verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xb8 \xd0\xb2\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f')),
                ('Message', models.TextField(verbose_name=b'\xd0\xa1\xd0\xbe\xd0\xbe\xd0\xb1\xd1\x89\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('Card_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATM.BankCard')),
            ],
            options={
                'db_table': 'Operation',
            },
        ),
    ]
